//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PersonalFinances.DATA.DataModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace PersonalFinances.DATA.POCO
{
    
    public partial class assetCategory
    {
     
        public int assetCategoryId { get; set; }
        public int dossierId { get; set; }
        public bool isAsset { get; set; }
        public string description { get; set; }
        public int numSubcategories { get; set; }

        public static void AddCategory(assetCategory cat)
        {
            PersonalFinancesDBEntities db = new PersonalFinancesDBEntities();

            var catEntity = new PersonalFinances.DATA.DataModel.assetCategory { dossierId=cat.dossierId,
                                                                                isAsset =cat.isAsset,
                                                                                description =cat.description};



            db.assetCategories.Add(catEntity);
            db.SaveChanges();
        }

        public static assetCategory GetCategory(int assetCategoryId)
        {
            PersonalFinancesDBEntities db = new PersonalFinancesDBEntities();

            var aC=db.assetCategories.Find(assetCategoryId);

            return  new POCO.assetCategory
                    {
                        dossierId = aC.dossierId,
                        assetCategoryId = aC.assetCategoryId,
                        description = aC.description,
                        isAsset = aC.isAsset

                    };

        }


        public static void UpdateCategory(POCO.assetCategory assetCategory)
        {
            PersonalFinancesDBEntities db = new PersonalFinancesDBEntities();

            var aC = db.assetCategories.Find(assetCategory.assetCategoryId);

            aC.dossierId = assetCategory.dossierId;
            aC.isAsset = assetCategory.isAsset;
            aC.description = assetCategory.description;

            db.Entry(aC).State = EntityState.Modified;
            db.SaveChanges();

        }

        public static void DeleteCategory(int dossierId, int assetCategoryId)
        {
            PersonalFinancesDBEntities db = new PersonalFinancesDBEntities();

            var aC = (from c in db.assetCategories
                      where c.assetCategoryId == assetCategoryId
                      && c.dossierId == dossierId
                      select c).Single();


            db.assetCategories.Remove(aC);
            db.SaveChanges();

        }

    }

}
