//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace PersonalFinances.DATA.POCO
{
    
    public partial class recordCategory
    {
     
        public int recordCategoryId { get; set; }
        public int dossierId { get; set; }
        public bool isExpense { get; set; }
        public string description { get; set; }

    }
}
