//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int assetId { get; set; }
        public int dossierId { get; set; }
        public decimal receivable { get; set; }
        public decimal payable { get; set; }
        public string description { get; set; }
        public string externalId { get; set; }
        public int assetSubcategoryId { get; set; }
    
        public virtual assetSubcategory assetSubcategory { get; set; }
        public virtual dossier dossier { get; set; }
    }
}
