//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assetCategory()
        {
            this.assetSubcategories = new HashSet<assetSubcategory>();
        }
    
        public int assetCategoryId { get; set; }
        public int dossierId { get; set; }
        public bool isAsset { get; set; }
        public string description { get; set; }
    
        public virtual dossier dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assetSubcategory> assetSubcategories { get; set; }
    }
}
