//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetSubcategoryView
    {
        public int dossierId { get; set; }
        public int assetSubcategoryId { get; set; }
        public int assetCategoryId { get; set; }
        public string categoryDescription { get; set; }
        public string description { get; set; }
        public bool isAsset { get; set; }
    }
}
