//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class importRecordTmp
    {
        public int importRecordTmpId { get; set; }
        public int dossierId { get; set; }
        public System.DateTime date { get; set; }
        public decimal revenue { get; set; }
        public decimal expense { get; set; }
        public Nullable<int> numOfDuplicates { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string description { get; set; }
        public string comment { get; set; }
    
        public virtual dossier dossier { get; set; }
    }
}
