//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class liability
    {
        public int liabilityId { get; set; }
        public int dossierId { get; set; }
        public decimal value { get; set; }
        public string description { get; set; }
    
        public virtual dossier dossier { get; set; }
    }
}
