//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinances.DATA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurrentRecord
    {
        public int recurrentRecordId { get; set; }
        public int dossierId { get; set; }
        public Nullable<int> recordSubcategoryId { get; set; }
        public System.DateTime beginDate { get; set; }
        public System.DateTime endDate { get; set; }
        public byte peridiocity { get; set; }
        public byte dayPeriod { get; set; }
        public Nullable<decimal> value { get; set; }
    
        public virtual dossier dossier { get; set; }
        public virtual recordSubcategory recordSubcategory { get; set; }
    }
}
